language: go

go:
  - 1.x
  - 1.6
  - 1.7.x
  #- master

branches:
  only:
  - develop
  - master

before_install:
  - go get -u github.com/revel/cmd/revel
  - go get github.com/joho/godotenv
  - cp .env.example .env

script:
  - revel test github.com/kllakk/revel.template